version: '3.9'

networks:
  neiro-net:

services:
  neiro-jaeger:
    image: jaegertracing/all-in-one:1.51
    container_name: neiro-jaeger
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
      - COLLECTOR_OTLP_ENABLED=true
    networks:
      - neiro-net
    ports:
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
      - "14250:14250"
      - "14268:14268"
      - "14269:14269"
      - "9411:9411"

  my_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my_service
    networks:
      - neiro-net
    ports:
      - "8260:8260"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - SERVICE_A_CONFIG_PATH=config/my_service/prod.yaml
    volumes:
      - "/var/tmp/my_service/cache:/app/cache"

volumes:
  data_source:
    driver: local